### ISSUE TITLE
Korrigering och några frågor

### ISSUE THREAD

**Issue by sandlunds** [riksantikvarieambetet/Faltregistrering#3]
Hej!

Noterade en grej för endpointen för GET /metadata

```
   '204':
          description: Metadata mottaget. Inget innehåll returneras.
          schema:
            type: string
```

schema-elementet borde tas bort

Noterade också att **PlaceringTyp** saknar fälten sorteringsordning och beskrivning. Jag är inte 100 på att de ska finnas, men jag antar det.

Mvh, Simon
