### ISSUE TITLE
Idnummer på fältlämningstyper

### ISSUE THREAD

**Issue by sandlunds** [riksantikvarieambetet/Faltregistrering#4]
Hej!

I swagger-definitionen står det följande om lämningstypen på fältlämningar:
```
lamningstyp_id:
        type: integer
        format: int32
        minimum: 1001
        description: Anger lämningstyp_id för lämningen. Ex, 1001= lämningstypen
          'Avrättningsplats'.
        example: 1035
```

Minumumvärdet ska alltså vara minst 1001. När jag kollar i datat verkar det NÄSTAN stämma för _ingående_ fältlämningstyper, där de nästan alltid är över 1001, förutom Boplats som har 102. Men här ligger alltså begränsningen på den sammansatta nivån (ingående lämningar kommer ju i ett underobjekt). Kanske har missuppfattat något :)
